services:
  backend:
    image: ${ECR_REGISTRYT}/marketverse-backend:${IMAGE_TAG}
    container_name: mern_marketverse-backend
    env_file:
      - .env
    expose:
      - "5000"
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - marketverse-net

  frontend:
    image: ${ECR_REGISTRYT}/marketverse-frontend:${IMAGE_TAG}
    container_name: mern-marketverse-frontend
    expose:
      - "80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - marketverse-net

  redis:
    image: redis:7-alpine
    container_name: marketverse-redis
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - marketverse-net

  nginx:
    image: nginx:alpine
    container_name: marketverse-nginx

    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro

    depends_on:
      - frontend
      - backend

    restart: unless-stopped

    networks:
      - marketverse-net

networks:
  marketverse-net:
    driver: bridge

volumes:
  redis-data: