name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # build Docker images
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Docker
        run: docker --version
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build backend
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/marketverse-backend:${{ github.sha }} \
            ./backend

      - name: Build frontend
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/marketverse-frontend:${{ github.sha }} \
            ./frontend
      # push to ECR
      - name: Push backend
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/marketverse-backend:${{ github.sha }}
      - name: Push frontend
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/marketverse-frontend:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      # tell EC2 to pull images
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      # restart containers
      - name: Deploy to EC2
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "cd /home/ec2-user/marketverse",
              "export ECR_REGISTRY=${{ secrets.ECR_REGISTRY }}",
              "export IMAGE_TAG=${{ github.sha }}",
              "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REGISTRY",
              "docker compose -f docker-compose.prod.yml pull",
              "docker compose -f docker-compose.prod.yml up -d"
            ]'
